### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by dizhipeng** [schacon/blink#110]
- [x] Write the code
- [ ] Write all the tests
- [x] Document the code

``` java
for(int i=0 ; i < 5 ; i++)
{
    System.out.println("i is : " + i);
}
```

``` python
for idx in range(10):
    print idx
```

> Whether 'tis Nobler in the mind to suffer
> The Slings and Arrows of outrageous Fortune

How big are these slings and in particular, these arrows?

:joy: 我TM笑cry了

◆冃.狌.交.伖，释.鲂.压.劦、棑.解.漃.瘼◆
█网.址：https://github.com/ █┊ :two_men_holding_hands: :two_men_holding_hands: :two_men_holding_hands: 

![3383197285673575](https://cloud.githubusercontent.com/assets/17174322/13010633/b2204baa-d1dd-11e5-845d-fe661caede00.jpg)

**Comment by ghost** [comment]
This cat is scary.
